### ISSUE TITLE
Consider using "attr" instead of "attributes"

### ISSUE THREAD

**Issue by premasagar** [gtzilla/fastFrag#1]
To reduce verbosity (it's quicker to write, and less clutter to look at), and to reduce filesize / memory footprint (useful, e.g. on mobile devices where the ungzipped size is all-important).

**Comment by gtzilla** [comment]
Thanks for the suggestion, sounds great. I would like to do some tests to make sure there aren't any jQuery conflicts, I believe they use .attrs() and .attr() to getter / setter methods

**Comment by premasagar** [comment]
Yes, jQuery uses attr(), but the fastFrag data objects won't conflict with that. The jQuery `attr()` method gets and sets attributes, so I think it makes sense for the fastFrag `attr` property to store a value for attributes.

**Comment by gtzilla** [comment]
True, directly they should not conflict, I supposed I meant it in the more general sense of causing confusion. Regardless, I have started a branch with this change so I can test against a few different browsers. Assuming all works as expected, I'll merge

http://github.com/gregory80/fastFrag/tree/syntax_changes

Into trunk and update both the docs and app engine to say 'attr' but support both attributes and attr for backwards compatability

thanks
-gregory

**Comment by premasagar** [comment]
OK, cool.
