### ISSUE TITLE
HTML to JSON

### ISSUE THREAD

**Issue by pvansteenoven** [gtzilla/fastFrag#13]
im a bit lost, how can i convert HTML into JSON? The readme only covers JSON to HTML

**Comment by gtzilla** [comment]
> Convert your existing HTML to fastFrag JSON in less than a second visit fastFrag converter, paste in HTML and get fastFrag JSON back.

http://json.fastfrag.org/
https://github.com/gregory80/fastFrag/blob/master/README.md#overview
