### ISSUE TITLE
Appspot converter doesn't convert sample text as expected

### ISSUE THREAD

**Issue by premasagar** [gtzilla/fastFrag#2]
On http://fastfrag-converter.appspot.com there is some sample markup. I clicked the "Convert" button several times, expecting it to convert the text - but nothing happened (or perhaps the page reloaded). I then clicked the "Sample Text" button, and then found that it converted. I was thinking that the two buttons had got mixed up with each other, but then found that if I did enter my own markup and clicked "Convert", it did indeed convert.

I'd suggest removing the "Sample Text" button, and having the "Convert" button actually convert the sample markup. People can refresh the page if they want to see the sample markup again.

**Comment by gtzilla** [comment]
Great points. I would like to add an actual 'see fastFrag' button, which could append to the DOM easily for testing as well, in addition to providing more sophisticated navigation in general. Currently, there is a bug when converting images wrapped in <a> tags in the actual parser that has held my attention.

Once the parser is more stable in general, Hope to improve this area.

**Comment by gtzilla** [comment]
add text area length check for button display. closed by 535b9cb9aae08fc96e3df8b04f9232397b34c8a4
