### ISSUE TITLE
IE7 requires camelCase for setAttribute

### ISSUE THREAD

**Issue by simpixelated** [gtzilla/fastFrag#8]
I ran into this while trying to use 'colspan' instead of 'colSpan', which IE7 ignored until I changed it to the latter. Here's some more information on the bug in IE7:
http://www.quirksmode.org/bugreports/archives/2005/07/Setting_accesskey_attribute_using_setAttribute_is_.html

A workaround could be to either always use camelCase (seems to work across most browsers, but haven't tested extensively) or convert to camelCase for IE7 only. 

http://jsfiddle.net/93PvZ/10/ (view in IE7 to see the problem)

**Comment by gtzilla** [comment]
Interesting, there is already an [exception in the code for ie7](https://github.com/gregory80/fastFrag/blob/master/js/fastFrag.js#L60), submitted by @jeffreytierney when it comes to setting the style attribute. I dont have any Window machines with ie7 available at the moment. If you have a clean patch, it would be welcomed.

**Comment by simpixelated** [comment]
Well, this may be a very slippery slope because you essentially need an [exception for every attribute in IE7](http://webbugtrack.blogspot.com/2007/08/bug-242-setattribute-doesnt-always-work.html). Most can be handled by converting to camelCase, but not all, and even then they are problematic. For example, I'm trying to get the value of a button element created with fastFrag. Unfortunately in IE7 it outputs the value to the button label and trying to access the actual value via Javascript just gives me the text label instead.
